package app

import (
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/zalando/go-keyring"
)

const keyFileEnv = "TODO_CONNECT_KEY_FILE"
const secretEnvelope = "TDC-AES256-GCM-1\x00"
const keyringService = "To Do Connect encryption key"

func protect(plain []byte) ([]byte, error) {
	if runtime.GOOS == "windows" && os.Getenv(keyFileEnv) == "" {
		return nativeProtect(plain)
	}
	key, err := encryptionKey(true)
	if err != nil {
		return nil, err
	}
	return sealSecret(key, plain)
}

func unprotect(data []byte) ([]byte, error) {
	if !bytes.HasPrefix(data, []byte(secretEnvelope)) {
		return nativeUnprotect(data)
	}
	key, err := encryptionKey(false)
	if err != nil {
		return nil, err
	}
	return openSecret(key, data)
}

func sealSecret(key, plain []byte) ([]byte, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	aead, err := cipher.NewGCMWithRandomNonce(block)
	if err != nil {
		return nil, err
	}
	return aead.Seal([]byte(secretEnvelope), nil, plain, []byte(secretEnvelope)), nil
}

func openSecret(key, data []byte) ([]byte, error) {
	if !bytes.HasPrefix(data, []byte(secretEnvelope)) {
		return nil, errors.New("unrecognized encrypted credential format")
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	aead, err := cipher.NewGCMWithRandomNonce(block)
	if err != nil {
		return nil, err
	}
	plain, err := aead.Open(nil, nil, data[len(secretEnvelope):], []byte(secretEnvelope))
	if err != nil {
		return nil, errors.New("credentials could not be decrypted: wrong encryption key or damaged file; existing data was not replaced")
	}
	return plain, nil
}

func encryptionKey(create bool) ([]byte, error) {
	if path := os.Getenv(keyFileEnv); path != "" {
		return readKeyFile(path)
	}
	if runtime.GOOS == "windows" {
		return nil, errors.New("this credential file uses portable encryption; set TODO_CONNECT_KEY_FILE to its original key file")
	}
	c, err := openConnections()
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(c.dir, 0700); err != nil {
		return nil, err
	}
	unlock, err := lockConnection(filepath.Join(c.dir, ".keyring.lock"))
	if err != nil {
		return nil, err
	}
	defer unlock()
	// Keyring entries are scoped to this local data directory, not a user's project name.
	digest := sha256.Sum256([]byte(c.dir))
	account := hex.EncodeToString(digest[:])
	encoded, err := keyring.Get(keyringService, account)
	if errors.Is(err, keyring.ErrNotFound) && create {
		entries, e := os.ReadDir(c.dir)
		if e != nil {
			return nil, e
		}
		for _, entry := range entries {
			if strings.HasSuffix(entry.Name(), ".secret") || strings.HasSuffix(entry.Name(), ".client") {
				return nil, errors.New("OS encryption key is missing but encrypted credentials exist; restore the original key or use the matching explicit key file")
			}
		}
		key := make([]byte, 32)
		if _, err := rand.Read(key); err != nil {
			return nil, err
		}
		encoded = hex.EncodeToString(key)
		if err := keyring.Set(keyringService, account, encoded); err != nil {
			return nil, errors.New("OS key storage is unavailable or locked; unlock your keychain or explicitly configure TODO_CONNECT_KEY_FILE; no plaintext fallback")
		}
		stored, err := keyring.Get(keyringService, account)
		if err != nil || stored != encoded {
			return nil, errors.New("OS key storage did not retain the new key; credentials were not written")
		}
	} else if err != nil {
		return nil, errors.New("OS encryption key is unavailable or locked; unlock the existing keychain or use the matching key file; no plaintext fallback")
	}
	key, err := hex.DecodeString(encoded)
	if err != nil || len(key) != 32 {
		return nil, errors.New("invalid key in OS credential storage")
	}
	return key, nil
}

func readKeyFile(path string) ([]byte, error) {
	if !filepath.IsAbs(path) {
		return nil, errors.New("TODO_CONNECT_KEY_FILE must be an absolute private key-file path")
	}
	f, err := os.Open(path)
	if err != nil {
		return nil, errors.New("could not open the encryption key file; existing credentials were not changed")
	}
	defer f.Close()
	info, err := f.Stat()
	if err != nil {
		return nil, err
	}
	if !info.Mode().IsRegular() {
		return nil, errors.New("encryption key must be a regular file")
	}
	if runtime.GOOS != "windows" && info.Mode().Perm()&0077 != 0 {
		return nil, errors.New("encryption key permissions must exclude group/other access; use mode 0600")
	}
	key, err := io.ReadAll(io.LimitReader(f, 33))
	if err != nil {
		return nil, err
	}
	if len(key) != 32 {
		return nil, errors.New("encryption key file must contain exactly 32 raw bytes generated by todo-connect keygen")
	}
	return key, nil
}

func generateKeyFile(path string) error {
	if !filepath.IsAbs(path) {
		return errors.New("keygen requires an absolute --out path outside repositories and synchronized folders")
	}
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return err
	}
	key := make([]byte, 32)
	if _, err := rand.Read(key); err != nil {
		return err
	}
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
	if errors.Is(err, os.ErrExist) {
		return errors.New("key file already exists; it will not be overwritten")
	}
	if err != nil {
		return err
	}
	_, writeErr := f.Write(key)
	closeErr := f.Close()
	if err := errors.Join(writeErr, closeErr); err != nil {
		return errors.Join(err, os.Remove(path))
	}
	return nil
}
